version: 2
updates:
  # === JavaScript Dependencies (Root/Frontend) ===
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '04:00'
      timezone: 'Etc/UTC'
    open-pull-requests-limit: 10
    labels:
      - 'dependencies'
      - 'npm'
      - 'frontend'
    commit-message:
      prefix: 'deps(frontend)'
      include: 'scope'
    groups:
      # Group related packages to reduce PR noise
      react-stack:
        patterns:
          - 'react'
          - 'react-dom'
          - '@types/react'
          - '@types/react-dom'
      vite-stack:
        patterns:
          - 'vite'
          - '@vitejs/*'
      testing-stack:
        patterns:
          - 'vitest'
          - '@testing-library/*'
          - 'playwright'
          - '@playwright/test'
      eslint-stack:
        patterns:
          - 'eslint'
          - 'eslint-*'
          - '@typescript-eslint/*'
    # Ignore major updates for all dependencies to avoid breaking changes
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']

  # === JavaScript Dependencies (Backend) ===
  - package-ecosystem: 'npm'
    directory: '/backend'
    schedule:
      interval: 'daily'
      time: '04:00'
      timezone: 'Etc/UTC'
    open-pull-requests-limit: 10
    labels:
      - 'dependencies'
      - 'npm'
      - 'backend'
    commit-message:
      prefix: 'deps(backend)'
      include: 'scope'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']

  # === Docker Dependencies ===
  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - 'dependencies'
      - 'docker'
    commit-message:
      prefix: 'chore(deps)'
      include: 'scope'

  # === GitHub Actions ===
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - 'dependencies'
      - 'github-actions'
      - 'ci'
    commit-message:
      prefix: 'ci(deps)'
      include: 'scope'
    # Group all GitHub Actions updates into a single PR
    groups:
       github-actions:
         patterns:
           - "*"
