version: '1'

services:
  backend:
    source: backend
    build:
      command: npm ci
    start:
      command: npx tsx src/server.ts
    environment:
      NODE_ENV: production
      PORT: 3001
      LOCAL_SQLITE: true
      DATABASE_PATH: /app/data/database.db
    healthcheck:
      path: /health
      timeout: 30
    restart:
      policy: on-failure
      max_retries: 10