[build]
builder = "nixpacks"
buildCommand = "npm ci"
watchPatterns = ["src/**/*", "package.json", "tsconfig.json"]

[deploy]
startCommand = "npx tsx src/server.ts"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 30
replicas = 1

[environments.production]
PORT = 3001
NODE_ENV = "production"
LOCAL_SQLITE = "true"

# Service configuration
[service]
name = "vibe-booking-api"

# Git branch settings
[source]
trigger = "main"

# Environment variables for Railway
[variables]
# SQLite for Railway deployment (simpler than PostgreSQL setup)
LOCAL_SQLITE = "true"
DATABASE_PATH = "/app/data/database.db"
NODE_ENV = "production"
PORT = "3001"