[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "npm run start:simple"
healthcheckPath = "/api/health"
healthcheckTimeout = 30
restartPolicyType = "on-failure"

[variables]
NODE_ENV = "production"
PORT = "3001"