global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'hotel-booking-monitor'

rule_files:
  - 'alerts.yml'

scrape_configs:
  - job_name: 'hotel-booking-app'
    static_configs:
      - targets: ['hotel-booking-app:3000']
    metrics_path: '/metrics'

  - job_name: 'hotel-booking-api'
    static_configs:
      - targets: ['hotel-booking-api:3001']
    metrics_path: '/metrics'

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
